corpus_pubformats = ('tar',
                     'zip',
                     #'pdf',
                     )

text_pubformats = ('gfm',
                   'html',
                   'markdown',
                   'docx',
                   'epub',
                   'odt',
                   #'pdf',   requires xetex
                   )

image_pubformats = ('bmp',
                    'eps',
                    'gif',
                    'jpeg',
                    'pdf',
                    'png',
                    'ppm',
                    'tga',
                    'tiff',
                    'webp',
                    )

text_upformats = (('markdown', 'Markdown'),
                  ('gfm', 'Markdown (github-flavour)'),
                  ('latex', 'LaTeX'),
                  ('docx', 'Word docx'),
                  ('odt', 'OpenDocument ODT'),
                  ('html', 'HTML'),
                  ('mediawiki', 'MediaWiki markup'),
                  ('rst', 'reStructuredText'),
                  ('json', 'JSON'),
                  ('native', 'Haskell (pandoc-native)'),
                  )

image_upformats = (('bmp', 'Windows bitmap'),
                   ('eps', 'Encapsulated PostScrip'),
                   ('gif', 'Graphics Interchange Format'),
                   ('jpeg', 'JPEG'),
                   ('jpeg2000', 'JPEG 2000'),
                   ('png', 'Portable Network Graphics'),
                   ('ppm', 'Netbpm portable pixmap'),
                   ('tga', 'Truevision Targa'),
                   ('tiff', 'Tagged Image File Format'),
                   ('webp', 'WebP'),
                   ('dds', 'DirectDraw Surface (DirectX)'),
                   ('fpx', 'Kodak FlashPix'),
                   ('gbr', 'Gimp brush'),
                   ('imt', 'Image tools'),
                   ('iptc/naa', 'IPTC/NAA newsphoto'),
                   ('mcidas', 'McIdas area'),
                   ('mic', 'Microsoft Image Composer'),
                   ('mpo', 'Multi Picture Object'),
                   ('psd', 'Photoshop Document'),
                   ('xpm', 'X PixMap'),
                   )
